### ISSUE TITLE
Project seems not commited completely

### ISSUE THREAD

**Issue by casaper** [Pernosco/DOMRec#4]
I also did not manage to get the script running, and I also found where the reasons are:

```
// List URLs explicitly here so use_content_hashes can
// rewrite them to point to content-hashes.
const DOMREC_REPLAY_FRAME_STYLESHEETS = {
  'source-viewer.css': '/client/source-viewer.css?1',
  'editor.main.css': '/client/monaco-editor/min/vs/editor/editor.main.css?1',
  'pml.css': '/client/pml.css?1'
};
const DOMREC_REPLAY_STYLESHEETS = [
  '/client/main.css',
  '/client/pml.css',
  '/client/domrec-replay.css'
];
```

These assets are not available and the script basically scrambles itself up in `rewriteResourceURL`

@rocallahan Is it possible that these Files are missing?

And How would the correct asset structure be?

Or is the script supposed to laod these monaco editor assets from a cdn?

**Comment by rocallahan** [comment]
Sorry, it's true that I forgot to land a couple of CSS files. I've just fixed that.

However, these are just the stylesheets loaded into the playback frame and any of its subframes, so you would need to change these lists to list the stylesheets used by your own application, plus the domrec-replay.css file that I just landed.

I guess I should create a sample that shows how to use this. The code I landed was just a snapshot of what we're using in Pernosco and is customized for our app.

**Comment by rocallahan** [comment]
If you don't use subframes you can leave that list empty, and the main.css/pml.css files are Pernosco stuff I should just remove.

**Comment by casaper** [comment]
@rocallahan 

> Sorry, it's true that I forgot to land a couple of CSS files. I've just fixed that.

No worries. Thanks for uploading.

> However, these are just the stylesheets loaded into the playback frame and any of its subframes, so you would need to change these lists to list the stylesheets used by your own application, plus the domrec-replay.css file that I just landed.

> I guess I should create a sample that shows how to use this. The code I landed was just a snapshot of what we're using in Pernosco and is customized for our app.

That would be highly appreciated. Thx allot!

**Comment by rocallahan** [comment]
Done. It's still not great but hopefully it's enough for someone motivated :-).
